apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis
          name: redis-store
      volumes:
      - name: redis-store
        hostPath:
          path: /opt/redis
