apiVersion: v1
kind: ReplicationController
metadata:
  name: votingapp
spec:
  template:
    metadata:
      labels:
        app: votingapp
        tier: frontend
    spec:
      containers:
      - name: votingapp
        image: surajd/votingapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
